exog_params:
  S_0: 100.
  K: 110.
  sig: .2
  T: 1.
  r: .05
  P_0: 10.7

expirement_1:
  rm_steps: 20_000
  M_steps: 1500
  alphas:
  - .95
  - .99
  - .995
  - .999

expirement_2:
  rm_steps: 50_000
  M_steps: 2500
  alphas:
  - .95
  - .99
  - .995
  - .999

expirement_3:
  rm_steps: 80_000
  M_steps: 3500
  alphas:
  - .95
  - .99
  - .995
  - .999
